// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pkg/plugins/proto/plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_pkg_plugins_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigResponse) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_plugins_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_plugin_proto_rawDescGZIP(), []int{1}
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_pkg_plugins_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *InitRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalPath     string                 `protobuf:"bytes,1,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	RemotePath    string                 `protobuf:"bytes,2,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_pkg_plugins_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *UploadRequest) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *UploadRequest) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemotePath    string                 `protobuf:"bytes,1,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	LocalPath     string                 `protobuf:"bytes,2,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_pkg_plugins_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *DownloadRequest) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

func (x *DownloadRequest) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_pkg_plugins_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *ListRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []string               `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_pkg_plugins_proto_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *ListResponse) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemotePath    string                 `protobuf:"bytes,1,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_pkg_plugins_proto_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRequest) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

var File_pkg_plugins_proto_plugin_proto protoreflect.FileDescriptor

const file_pkg_plugins_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1epkg/plugins/proto/plugin.proto\x12\fbackupplugin\"\x8d\x01\n" +
	"\x0eConfigResponse\x12@\n" +
	"\x06config\x18\x01 \x03(\v2(.backupplugin.ConfigResponse.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\a\n" +
	"\x05Empty\"\x87\x01\n" +
	"\vInitRequest\x12=\n" +
	"\x06config\x18\x01 \x03(\v2%.backupplugin.InitRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\rUploadRequest\x12\x1d\n" +
	"\n" +
	"local_path\x18\x01 \x01(\tR\tlocalPath\x12\x1f\n" +
	"\vremote_path\x18\x02 \x01(\tR\n" +
	"remotePath\"Q\n" +
	"\x0fDownloadRequest\x12\x1f\n" +
	"\vremote_path\x18\x01 \x01(\tR\n" +
	"remotePath\x12\x1d\n" +
	"\n" +
	"local_path\x18\x02 \x01(\tR\tlocalPath\"%\n" +
	"\vListRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"$\n" +
	"\fListResponse\x12\x14\n" +
	"\x05files\x18\x01 \x03(\tR\x05files\"0\n" +
	"\rDeleteRequest\x12\x1f\n" +
	"\vremote_path\x18\x01 \x01(\tR\n" +
	"remotePath2\x91\x03\n" +
	"\bProvider\x126\n" +
	"\x04Init\x12\x19.backupplugin.InitRequest\x1a\x13.backupplugin.Empty\x12>\n" +
	"\n" +
	"UploadFile\x12\x1b.backupplugin.UploadRequest\x1a\x13.backupplugin.Empty\x12B\n" +
	"\fDownloadFile\x12\x1d.backupplugin.DownloadRequest\x1a\x13.backupplugin.Empty\x12B\n" +
	"\tListFiles\x12\x19.backupplugin.ListRequest\x1a\x1a.backupplugin.ListResponse\x12>\n" +
	"\n" +
	"DeleteFile\x12\x1b.backupplugin.DeleteRequest\x1a\x13.backupplugin.Empty\x12E\n" +
	"\x10GetUpdatedConfig\x12\x13.backupplugin.Empty\x1a\x1c.backupplugin.ConfigResponseB8Z6github.com/CliffJumper/secure-backup/pkg/plugins/protob\x06proto3"

var (
	file_pkg_plugins_proto_plugin_proto_rawDescOnce sync.Once
	file_pkg_plugins_proto_plugin_proto_rawDescData []byte
)

func file_pkg_plugins_proto_plugin_proto_rawDescGZIP() []byte {
	file_pkg_plugins_proto_plugin_proto_rawDescOnce.Do(func() {
		file_pkg_plugins_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugins_proto_plugin_proto_rawDesc), len(file_pkg_plugins_proto_plugin_proto_rawDesc)))
	})
	return file_pkg_plugins_proto_plugin_proto_rawDescData
}

var file_pkg_plugins_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_plugins_proto_plugin_proto_goTypes = []any{
	(*ConfigResponse)(nil),  // 0: backupplugin.ConfigResponse
	(*Empty)(nil),           // 1: backupplugin.Empty
	(*InitRequest)(nil),     // 2: backupplugin.InitRequest
	(*UploadRequest)(nil),   // 3: backupplugin.UploadRequest
	(*DownloadRequest)(nil), // 4: backupplugin.DownloadRequest
	(*ListRequest)(nil),     // 5: backupplugin.ListRequest
	(*ListResponse)(nil),    // 6: backupplugin.ListResponse
	(*DeleteRequest)(nil),   // 7: backupplugin.DeleteRequest
	nil,                     // 8: backupplugin.ConfigResponse.ConfigEntry
	nil,                     // 9: backupplugin.InitRequest.ConfigEntry
}
var file_pkg_plugins_proto_plugin_proto_depIdxs = []int32{
	8, // 0: backupplugin.ConfigResponse.config:type_name -> backupplugin.ConfigResponse.ConfigEntry
	9, // 1: backupplugin.InitRequest.config:type_name -> backupplugin.InitRequest.ConfigEntry
	2, // 2: backupplugin.Provider.Init:input_type -> backupplugin.InitRequest
	3, // 3: backupplugin.Provider.UploadFile:input_type -> backupplugin.UploadRequest
	4, // 4: backupplugin.Provider.DownloadFile:input_type -> backupplugin.DownloadRequest
	5, // 5: backupplugin.Provider.ListFiles:input_type -> backupplugin.ListRequest
	7, // 6: backupplugin.Provider.DeleteFile:input_type -> backupplugin.DeleteRequest
	1, // 7: backupplugin.Provider.GetUpdatedConfig:input_type -> backupplugin.Empty
	1, // 8: backupplugin.Provider.Init:output_type -> backupplugin.Empty
	1, // 9: backupplugin.Provider.UploadFile:output_type -> backupplugin.Empty
	1, // 10: backupplugin.Provider.DownloadFile:output_type -> backupplugin.Empty
	6, // 11: backupplugin.Provider.ListFiles:output_type -> backupplugin.ListResponse
	1, // 12: backupplugin.Provider.DeleteFile:output_type -> backupplugin.Empty
	0, // 13: backupplugin.Provider.GetUpdatedConfig:output_type -> backupplugin.ConfigResponse
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_plugins_proto_plugin_proto_init() }
func file_pkg_plugins_proto_plugin_proto_init() {
	if File_pkg_plugins_proto_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugins_proto_plugin_proto_rawDesc), len(file_pkg_plugins_proto_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_plugins_proto_plugin_proto_goTypes,
		DependencyIndexes: file_pkg_plugins_proto_plugin_proto_depIdxs,
		MessageInfos:      file_pkg_plugins_proto_plugin_proto_msgTypes,
	}.Build()
	File_pkg_plugins_proto_plugin_proto = out.File
	file_pkg_plugins_proto_plugin_proto_goTypes = nil
	file_pkg_plugins_proto_plugin_proto_depIdxs = nil
}
