// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/credentials/proto/plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_pkg_credentials_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_credentials_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_credentials_proto_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   map[string]string      `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_pkg_credentials_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_credentials_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_credentials_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetCredentials() map[string]string {
	if x != nil {
		return x.Credentials
	}
	return nil
}

var File_pkg_credentials_proto_plugin_proto protoreflect.FileDescriptor

const file_pkg_credentials_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"\"pkg/credentials/proto/plugin.proto\x12\x10credentialplugin\"$\n" +
	"\n" +
	"GetRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\"\x9f\x01\n" +
	"\vGetResponse\x12P\n" +
	"\vcredentials\x18\x01 \x03(\v2..credentialplugin.GetResponse.CredentialsEntryR\vcredentials\x1a>\n" +
	"\x10CredentialsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012c\n" +
	"\x12CredentialProvider\x12M\n" +
	"\x0eGetCredentials\x12\x1c.credentialplugin.GetRequest\x1a\x1d.credentialplugin.GetResponseB<Z:github.com/CliffJumper/secure-backup/pkg/credentials/protob\x06proto3"

var (
	file_pkg_credentials_proto_plugin_proto_rawDescOnce sync.Once
	file_pkg_credentials_proto_plugin_proto_rawDescData []byte
)

func file_pkg_credentials_proto_plugin_proto_rawDescGZIP() []byte {
	file_pkg_credentials_proto_plugin_proto_rawDescOnce.Do(func() {
		file_pkg_credentials_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_credentials_proto_plugin_proto_rawDesc), len(file_pkg_credentials_proto_plugin_proto_rawDesc)))
	})
	return file_pkg_credentials_proto_plugin_proto_rawDescData
}

var file_pkg_credentials_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_credentials_proto_plugin_proto_goTypes = []any{
	(*GetRequest)(nil),  // 0: credentialplugin.GetRequest
	(*GetResponse)(nil), // 1: credentialplugin.GetResponse
	nil,                 // 2: credentialplugin.GetResponse.CredentialsEntry
}
var file_pkg_credentials_proto_plugin_proto_depIdxs = []int32{
	2, // 0: credentialplugin.GetResponse.credentials:type_name -> credentialplugin.GetResponse.CredentialsEntry
	0, // 1: credentialplugin.CredentialProvider.GetCredentials:input_type -> credentialplugin.GetRequest
	1, // 2: credentialplugin.CredentialProvider.GetCredentials:output_type -> credentialplugin.GetResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_credentials_proto_plugin_proto_init() }
func file_pkg_credentials_proto_plugin_proto_init() {
	if File_pkg_credentials_proto_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_credentials_proto_plugin_proto_rawDesc), len(file_pkg_credentials_proto_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_credentials_proto_plugin_proto_goTypes,
		DependencyIndexes: file_pkg_credentials_proto_plugin_proto_depIdxs,
		MessageInfos:      file_pkg_credentials_proto_plugin_proto_msgTypes,
	}.Build()
	File_pkg_credentials_proto_plugin_proto = out.File
	file_pkg_credentials_proto_plugin_proto_goTypes = nil
	file_pkg_credentials_proto_plugin_proto_depIdxs = nil
}
