// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: pkg/credentials/proto/plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CredentialProvider_GetCredentials_FullMethodName = "/credentialplugin.CredentialProvider/GetCredentials"
)

// CredentialProviderClient is the client API for CredentialProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CredentialProviderClient interface {
	GetCredentials(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type credentialProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewCredentialProviderClient(cc grpc.ClientConnInterface) CredentialProviderClient {
	return &credentialProviderClient{cc}
}

func (c *credentialProviderClient) GetCredentials(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, CredentialProvider_GetCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CredentialProviderServer is the server API for CredentialProvider service.
// All implementations must embed UnimplementedCredentialProviderServer
// for forward compatibility.
type CredentialProviderServer interface {
	GetCredentials(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedCredentialProviderServer()
}

// UnimplementedCredentialProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCredentialProviderServer struct{}

func (UnimplementedCredentialProviderServer) GetCredentials(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCredentials not implemented")
}
func (UnimplementedCredentialProviderServer) mustEmbedUnimplementedCredentialProviderServer() {}
func (UnimplementedCredentialProviderServer) testEmbeddedByValue()                            {}

// UnsafeCredentialProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CredentialProviderServer will
// result in compilation errors.
type UnsafeCredentialProviderServer interface {
	mustEmbedUnimplementedCredentialProviderServer()
}

func RegisterCredentialProviderServer(s grpc.ServiceRegistrar, srv CredentialProviderServer) {
	// If the following call pancis, it indicates UnimplementedCredentialProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CredentialProvider_ServiceDesc, srv)
}

func _CredentialProvider_GetCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialProviderServer).GetCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialProvider_GetCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialProviderServer).GetCredentials(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CredentialProvider_ServiceDesc is the grpc.ServiceDesc for CredentialProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CredentialProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "credentialplugin.CredentialProvider",
	HandlerType: (*CredentialProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCredentials",
			Handler:    _CredentialProvider_GetCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/credentials/proto/plugin.proto",
}
